#undef TAPPING_TERM
#define TAPPING_TERM 300

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "YRYG4/v66a3O"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1

#define RGB_MATRIX_STARTUP_SPD 60

